return {
    SavedKey = nil,
    AutoValidate = false,

    -- Combat
    FrameTP = true,
    OneFrameDelay = false,
    RapidFire = true,

    -- Aimbot
    Aimbot_Enabled = false,
    Aimbot_ToggleMode = false,
    Aimbot_StickyTarget = false,
    Aimbot_Smoothness = 15,
    Aimbot_FOV = 60,
    Aimbot_ShowFOV = true,
    Aimbot_FOVColor = Color3.fromRGB(255, 105, 180),
    Aimbot_TargetPart = "Head",
    Aimbot_Priority = "Closest to Mouse",
    Aimbot_TeamCheck = false,
    Aimbot_WallCheck = false,

    -- Visuals
    FOV_Enabled = true,
    FOV_Radius = 250,
    FOV_Color = Color3.fromRGB(255, 80, 80),
    Tracers = true,
    Tracer_Color = Color3.fromRGB(255, 60, 60),
    Hitmarkers = true,
    Highlights = true,
    ESP_Enabled = false,
    ESP_Boxes = false,
    ESP_Box3D = false,
    ESP_Names = false,
    ESP_Distance = false,
    ESP_Health = false,
    ESP_Skeleton = false,
    ESP_Chams = false,
    ESP_HeadDot = false,
    ESP_WeaponNames = false,
    ESP_TeamCheck = false,
    ESP_DistanceToggle = false,
    ESP_MaxDistance = 2000,
    ESP_TargetMode = false,
    ESP_BoxThickness = 1,
    ESP_HeadDotThickness = 1,
    ESP_HeadDotSize = 0.5,
    ESP_Colors = {
        Box = Color3.fromRGB(255, 105, 180),
        Name = Color3.fromRGB(255, 255, 255),
        Distance = Color3.fromRGB(200, 200, 200),
        Health = Color3.fromRGB(0, 255, 100),
        Skeleton = Color3.fromRGB(255, 255, 255),
        ChamsFill = Color3.fromRGB(255, 105, 180),
        ChamsOutline = Color3.fromRGB(255, 255, 255),
        Tracers = Color3.fromRGB(255, 105, 180),
        HeadDot = Color3.fromRGB(255, 255, 255),
    },

    -- Target
    Spectate = false,
    TargetPart = "Head",
    TargetMode = "Closest",
    MaxTargetDistance = 5000000000000000,

    -- Farm
    FarmEnabled = false,
    FarmDistance = 12,
    FarmVerticalOffset = 0,
    FarmPullSpeed = 1,

    -- Misc
    AntiStomp = false,
    AntiStompMode = "Void",
    AntiStompThreshold = 50,
    SpamEnabled = false,
    SpamRange = "Close",
    SpamCloseHeight = 350,
    SpamCloseRadius = 250,
    SpamCloseVerticalJitter = 50,
    SpamFarBase = Vector3.new(500000, 500000, 500000),
    SpamFarJitter = 5000,
    SpamSpeed = 1,
    AutoArmor = false,
    AutoArmorOnDamage = false,
    AutoArmorPos = Vector3.new(-934.12, -25.38, 571.02),
    AutoArmorTriggerHealth = 50,
    AutoArmorCooldown = 1,

    -- World
    World_Fullbright = false,
    World_NoFog = false,
    World_CustomTime = false,
    World_TimeOfDay = 12,
    World_Brightness = 10,
    World_NoShadows = false,
    World_NoAtmosphere = false,
    World_NoSunRays = false,
    World_NoColorCorrection = false,
    World_LowGFX = false,

    -- Movement
    Move_SpeedEnabled = false,
    Move_Speed = 50,
    Move_HighJumpEnabled = false,
    Move_JumpPower = 100,
    Move_BunnyHop = false,
    Move_InfiniteJump = false,
    Move_NoClip = false,
    Move_Fly = false,
    Move_FlyMethod = "Tween",
    Move_FlySpeed = 50,
    Move_FlyKey = Enum.KeyCode.F,

    -- UI
    ToggleKey = Enum.KeyCode.RightShift,
    ShowHotkeys = true,

    -- Keybinds
    FrameTPKey = nil,
    OneFrameDelayKey = nil,
    RapidFireKey = nil,
    SpectateKey = nil,
    AntiStompKey = nil,
    SpamEnabledKey = nil,
    FarmEnabledKey = nil,
    Aimbot_EnabledKey = nil,
    Move_SpeedEnabledKey = nil,
    Move_HighJumpEnabledKey = nil,
    Move_BunnyHopKey = nil,
    Move_InfiniteJumpKey = nil,
    Move_NoClipKey = nil,
}