return {
    FrameTP = true,
    OneFrameDelay = false,
    RapidFire = true,
    FOV_Enabled = true,
    FOV_Radius = 250,
    FOV_Color = Color3.fromRGB(255, 80, 80),
    Tracers = true,
    Tracer_Color = Color3.fromRGB(255, 60, 60),
    Hitmarkers = true,
    Highlights = true,
    Spectate = false,
    TargetPart = "Head",
    TargetMode = "Closest",
    MaxTargetDistance = 5000000000000000,
    ToggleKey = Enum.KeyCode.RightShift,
    ShowHotkeys = true,
    -- Toggle hotkeys (nil = unbound)
    FrameTPKey = nil,
    OneFrameDelayKey = nil,
    RapidFireKey = nil,
    SpectateKey = nil,
}